### ISSUE TITLE
[Refactor] Migrate Windows functions to the windows crate

### ISSUE THREAD

**Issue by mttaggart** [mttaggart/OffensiveNotion#102]
This is a _big_ lift, but once done, the Windows components will be much more ergonomic. 

- [x] `elevate.rs`
- [x] `getprivs.rs`
- [x] `inject.rs`
- [x] `selfdestruct.rs`

**Comment by HuskyHacks** [comment]
Impl in https://github.com/mttaggart/OffensiveNotion/commits/dev
