### ISSUE TITLE
[New Feature] `exfil`

### ISSUE THREAD

**Issue by HuskyHacks** [mttaggart/OffensiveNotion#108]
For moving data out of the target environment

Crude proto function implemented in https://github.com/mttaggart/OffensiveNotion/commit/b89c5c3a82f9d5a04ab185671d3fb1eb86d8c0a5

- [ ] If file is large, make a sub-page and post to that page
- [ ] Pressure test
- [ ] Documentation

**Comment by mttaggart** [comment]
Closed in favor of [`s3upload`/`azupload`](https://github.com/mttaggart/OffensiveNotion/issues/121)
