### ISSUE TITLE
[New Feature] `getsystem`

### ISSUE THREAD

**Issue by mttaggart** [mttaggart/OffensiveNotion#114]
Allow elevation on Windows from High integrity sessions to `NT Authority\SYSTEM`. 

Looking at [this] from SharpDPAPI as inspiration: https://github.com/GhostPack/SharpDPAPI/blob/81e1fcdd44e04cf84ca0085cf5db2be4f7421903/SharpDPAPI/lib/Helpers.cs#L400

**Comment by HuskyHacks** [comment]
like a BOSS https://github.com/mttaggart/OffensiveNotion/commit/12b6112d9ffb1b2adcbba39138def8c9d16cf9c4
