### ISSUE TITLE
[New Feature] CreateThread Self Injection Option for `inject` (Windows Agent)

### ISSUE THREAD

**Issue by HuskyHacks** [mttaggart/OffensiveNotion#50]
Using VirtualAlloc/VirtualProtect/CreateThread/WaitForSingleObject pattern

**Comment by mttaggart** [comment]
This capability has been added to `inject.rs` as of 266b2f4f7d1a1b2770786965cae0e62d136c4f70

**Comment by HuskyHacks** [comment]
CreateThread injector now folded into `inject` command handler. Usage:
```
- [ ] inject self [url] [b64_iterations] 🎯 
```
Omitting the WaitForSingleObject call makes it so the agent can continue to function when the injection takes place.
