### ISSUE TITLE
[Refac/New Feature] Robust arg parsing for command `handle` functions 

### ISSUE THREAD

**Issue by HuskyHacks** [mttaggart/OffensiveNotion#53]

**Comment by mttaggart** [comment]
Args are now iterators, passed to commands and able to be unwrapped with defaults. Completed in 266b2f4f7d1a1b2770786965cae0e62d136c4f70

**Comment by mttaggart** [comment]
Let's review functionality and guarantee nothing got broken.

**Comment by mttaggart** [comment]
Closing for now; leaving the contract experiment for another time. Iterators provide pretty substantial safety with `unwrap_or_default()` and `unwrap_or_else()`
