### ISSUE TITLE
[HeisenBug] Potential bug where agent panics if attempting self delete

### ISSUE THREAD

**Issue by HuskyHacks** [mttaggart/OffensiveNotion#82]
Might be a bug when Linux (and maybe macOS) agent attempts to selfdestruct but does not have write access to the directory to be able to manipulate the file. Weird edge case and I can't seem to reproduce it but it did happen that one time

**Comment by mttaggart** [comment]
Fixed in 3fde2322df88caf7fbe4078e4091b985f00ee5b2
