### ISSUE TITLE
[New Feature] Execution Guard Rails (Username, Hostname, Domain/IsDomainJoined)

### ISSUE THREAD

**Issue by HuskyHacks** [mttaggart/OffensiveNotion#83]
red team responsibly, kiddos

**Comment by HuskyHacks** [comment]
- [x] Username
- [ ] Hostname
- [ ] Domain name
- [ ] Is Domain Joined?

**Comment by HuskyHacks** [comment]
Domain guardrail can be implemented similarly to Tetanus agent

https://github.com/MythicAgents/tetanus/blob/main/Payload_Type/tetanus/agent_code/src/utils/windows.rs#L98

@MEhrn00

**Comment by MEhrn00** [comment]
The [NetGetJoinInformation](https://docs.microsoft.com/en-us/windows/win32/api/lmjoin/nf-lmjoin-netgetjoininformation) winapi function can be used to get the domain name along with determining if the computer is domain joined or workgroup joined. The implementation I have in tetanus only returns the domain name for the system and not its domain joined status.

This looks like a better API function than what I have right now so I may migrate to it later in the future. Luckily, it's included in the winapi crate https://docs.rs/winapi/latest/winapi/um/lmjoin/fn.NetGetJoinInformation.html.

I could try to knock this out if you would like?

**Comment by HuskyHacks** [comment]
@MEhrn00 I haven't forgotten about this! I did some tests last night on my SLOTHCO domain controller and made some changes to the code, I'll pull this into your branch tonight so you can see

**Comment by HuskyHacks** [comment]
Impl in https://github.com/mttaggart/OffensiveNotion/commit/9c4b547e1bc7acd5ee7693d121685fd386da437b by @MEhrn00! Ty fam 🤘
