### ISSUE TITLE
[New Feature] `config`: now for printing and saving configs!

### ISSUE THREAD

**Issue by HuskyHacks** [mttaggart/OffensiveNotion#85]
Similar to `sleep` and `jitter`:

- [ ] Command returns the current config values to the page if run with no args
- [ ] Command changes a config value to something new if passed args

**Comment by mttaggart** [comment]
So we do have a `save` command. Do you imagine `saveconfig` any differently?

**Comment by mttaggart** [comment]
I propose unifying this into a single `config` command. No args would return the config, and `config sleep 10` would change that config option.

**Comment by HuskyHacks** [comment]
good deal!

**Comment by mttaggart** [comment]
Implemented in be17aad.
